services:
  postgres:
    image: postgres:17-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitly_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.3-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
 
volumes:
  postgres_data:
