services:
  postgres:
    image: postgres:17-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitly_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
  
  redis-replica1:
    image: redis:7-alpine
    container_name: redis-replica1
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes", "--replicaof", "redis-master", "6379"]
    depends_on:
      - redis-master

  redis-replica2:
    image: redis:7-alpine
    container_name: redis-replica2
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes", "--replicaof", "redis-master", "6379"]
    depends_on:
      - redis-master

  sentinel1:
    image: redis:7-alpine
    container_name: sentinel1
    ports:
      - "26379:26379"
    command:
      - redis-sentinel
      - /etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2

  sentinel2:
    image: redis:7-alpine
    container_name: sentinel2
    ports:
      - "26380:26379"
    command:
      - redis-sentinel
      - /etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2

  sentinel3:
    image: redis:7-alpine
    container_name: sentinel3
    ports:
      - "26381:26379"
    command:
      - redis-sentinel
      - /etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2

volumes:
  postgres_data:
